import { ProjectProps } from "./interfaces";

export const projects: ProjectProps[] = [
  {
    id: "s-house",
    title: "The Sharma Residence",
    subtitle:
      "Discover the Sharma family's journey to transform their bustling city home into a serene sanctuary where simplicity meets elegance amidst the vibrant streets of Delhi.",
    description:
      "In the bustling heart of Delhi, the Sharma family, known for their punctuality, dreamed of turning their 2500 sqm home into a peaceful retreat, where simplicity meets elegance. They wanted neutral colors and lots of natural light from the north-facing windows. We carefully planned each room to flow smoothly into the next, making sure every corner felt connected and calm. From the cozy bedrooms with soft fabrics to the modern kitchen and welcoming living room, every space felt harmonious. Big windows framed beautiful views of the bustling city streets, and the seamless flooring made the whole house feel bright and open. Even the bathrooms and puja room were designed with care, using soft colors to create a sense of peace. In the end, the Sharma residence became a testament to the power of thoughtful design, inviting everyone to experience serenity and balance amidst the busy city life of Delhi.",
    area: "900",
    category: "Residential",
    location: "Delhi",
    timeline: "2023",
    images: [
      "/images/s-house/entry.png",
      "/images/s-house/lampside.png",
      "/images/s-house/lobby_view_1.png",
      "/images/s-house/lobby_view_2.png",
      "/images/s-house/bed_1.png",
      "/images/s-house/bed_2.png",
      "/images/s-house/tv.png",
      "/images/s-house/kitchen.png",
      "/images/s-house/puja.png",
      "/images/s-house/elevation.png",
    ],
  },
  {
    id: "v-house",
    title: "The Vashist Residence",
    subtitle:
      "Urban Haven: The Vashist Family's multi generational Cozy Oasis in Delhi.",
    description:
      "Explore the Vashist family's journey in converting their vibrant city dwelling into a tranquil oasis where simplicity harmonizes with sophistication amid the lively streets of Delhi. Perched in the heart of Delhi, this intimate 1000 sq m residence serves as a sanctuary for a dynamic family. What sets it apart? Well, to begin, we opted to retain the majestic tree in front. Sure, we could have removed it, but why? That tree functions as a shield, muffling the clamor of traffic. Moreover, its luxuriant foliage affords us a degree of seclusion from the urban commotion. Thus, when you're unwinding on the upper floors, you're not subjected to the sight of cars whizzing past—thank you, tree! Indoors, the focus is on ensuring that each space exudes a sense of coziness and refinement. From the walk-in closets to the snug corners, every element is customized for the inhabitants. Additionally, with copious amounts of natural light streaming in, it feels akin to bringing the outdoors inside. Therefore, if you seek a residence where nature and luxury seamlessly intertwine, you've discovered it. Welcome to your new abode, where the tree outside is not merely a tree—it's an integral member of the family.",
    area: "1000",
    category: "Residential",
    location: "Delhi",
    timeline: "2018 - 2020",
    images: [
      "/images/v-house/living_room_view_b.png",
      "/images/v-house/living_room_view_a.png",
      "/images/v-house/living_room_view_c.png",
      "/images/v-house/living_room_view_d.png",
      "/images/v-house/bedroom_a.png",
      "/images/v-house/bedroom_a_alt.png",
      "/images/v-house/bedroom_b.png",
      "/images/v-house/bedroom_b_tv.png",
      "/images/v-house/guest_room.png",
      "/images/v-house/guest_room_front.png",
      "/images/v-house/guest_room_console.png",
      "/images/v-house/guest_room_wardrobe.png",
      "/images/v-house/kids_room.png",
      "/images/v-house/kids_room_wardrobe.png",
      "/images/v-house/study_table.png",
      "/images/v-house/entry_cupboard.png",
    ],
  },
  {
    id: "p-house",
    title: "The Paul Residence",
    subtitle: "Interior Design Transformation of a 170 sqm Apartment.",
    description:
      "In the bustling urban landscape, a 170 sqm apartment on the third floor underwent a remarkable interior design transformation, merging two flats into one cohesive living space. The 170 sqm apartment underwent structural upgrades, including wall demolitions and additions, as part of its interior design transformation. The site also underwent  waterproofing treatment for the  roof.  Key enhancements include an expanded kitchen, three spacious bedrooms with attached toilets and ample storage, a versatile family area with an adjacent bar, a sophisticated formal living room, and efficient laundry and supporting services. The kitchen now boasts modern appliances, sleek countertops, and generous storage, catering to culinary enthusiasts. Luxurious bedrooms offer tranquility and convenience with attached toilets and expanded cupboards for storage needs. The family area adapts to diverse activities, complemented by a stylish bar for entertaining guests. The formal living room exudes elegance with curated furnishings and ample natural light. At the rear, the laundry and supporting services area ensures seamless daily routines. A versatile bare area near the family space invites customization to reflect residents' preferences. This interior design project harmonizes aesthetics with functionality, culminating in an elevated living space that encapsulates the unique lifestyle and personality of its occupants, embodying the transformative potential of design.",
    area: "170",
    category: "Residential",
    location: "Vikaspuri",
    timeline: "2022 - 2023",
    images: [
      "/images/p-house/bar.png",
      "/images/p-house/bath_2.png",
      "/images/p-house/bed_2.png",
      "/images/p-house/bed_3.png",
      "/images/p-house/bed.png",
      "/images/p-house/fridge_side.png",
      "/images/p-house/kitchen_2.png",
      "/images/p-house/kitchen_3.png",
      "/images/p-house/kitchen.png",
      "/images/p-house/living_2.png",
      "/images/p-house/living.png",
      "/images/p-house/tv.png",
    ],
  },
];
