enum Status {
  PENDING = "PENDING",
  COMPLETE = "COMPLETE",
  FAILED = "FAILED",
}

enum SdVersion {
  v1_5 = "v1_5",
  v2 = "v2",
  v3 = "v3",
  SDXL_0_8 = "SDXL_0_8",
  SDXL_0_9 = "SDXL_0_9",
  SDXL_1_0 = "SDXL_1_0",
  SDXL_LIGHTNING = "SDXL_LIGHTNING",
}

enum Scheduler {
  KLMS = "KLMS",
  EULER_ANCESTRAL_DISCRETE = "EULER_ANCESTRAL_DISCRETE",
  EULER_DISCRETE = "EULER_DISCRETE",
  DDIM = "DDIM",
  DPM_SOLVER = "DPM_SOLVER",
  PNDM = "PNDM",
  LEONARDO = "LEONARDO",
}

enum PresetStyle {
  NIME = "NIME",
  BOKEH = "BOKEH",
  CINEMATIC = "CINEMATIC",
  CINEMATIC_CLOSEUP = "CINEMATIC_CLOSEUP",
  CREATIVE = "CREATIVE",
  DYNAMIC = "DYNAMIC",
  ENVIRONMENT = "ENVIRONMENT",
  FASHION = "FASHION",
  FILM = "FILM",
  FOOD = "FOOD",
  GENERAL = "GENERAL",
  HDR = "HDR",
  ILLUSTRATION = "ILLUSTRATION",
  LEONARDO = "LEONARDO",
  LONG_EXPOSURE = "LONG_EXPOSURE",
  MACRO = "MACRO",
  MINIMALISTIC = "MINIMALISTIC",
  MONOCHROME = "MONOCHROME",
  MOODY = "MOODY",
  NONE = "NONE",
  NEUTRAL = "NEUTRAL",
  PHOTOGRAPHY = "PHOTOGRAPHY",
  PORTRAIT = "PORTRAIT",
  RAYTRACED = "RAYTRACED",
  RENDER_3D = "RENDER_3D",
  RETRO = "RETRO",
  SKETCH_BW = "SKETCH_BW",
  SKETCH_COLOR = "SKETCH_COLOR",
  STOCK_PHOTO = "STOCK_PHOTO",
  VIBRANT = "VIBRANT",
  UNPROCESSED = "UNPROCESSED",
}

enum TransformType {
  OUTPAINT = "OUTPAINT",
  INPAINT = "INPAINT",
  UPSCALE = "UPSCALE",
  UNZOOM = "UNZOOM",
  NOBG = "NOBG",
}

export { Status, SdVersion, Scheduler, PresetStyle, TransformType };
